CREATE DATABASE QuanLyQuanAo
GO

USE QuanLyQuanAo
GO

CREATE TABLE Staff
(
	IDAccount INT IDENTITY
		CONSTRAINT PK_IDAccount PRIMARY KEY,
	Username NVARCHAR(100) NOT NULL,
	Password NVARCHAR(1000) NOT NULL,
	Status INT NOT NULL DEFAULT 0,
	Name NVARCHAR(50) NOT NULL,
	Address NVARCHAR(100),
	Phone NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50)
)
GO


CREATE TABLE Type
(
	IDType INT IDENTITY
		CONSTRAINT PK_IDType PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL DEFAULT N'Chưa đặt tên'
)
GO


CREATE TABLE Branch
(
	IDBranch INT IDENTITY
		CONSTRAINT PK_IDBranch PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL DEFAULT N'Chưa đặt tên'
)
GO


CREATE TABLE Supplier
(	
	IDSupplier INT IDENTITY
		CONSTRAINT PK_IDSupplier PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Address NVARCHAR(100),
	Phone NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50),
	IDBranch INT DEFAULT 1,
)


CREATE TABLE BillImport
(
	IDBillImport INT IDENTITY
		CONSTRAINT PK_IDBillImport PRIMARY KEY,
	IDSupplier INT NOT NULL DEFAULT 1,
	DateIn DATETIME NOT NULL,
)
GO

CREATE TABLE BillImportInfo
(
	IDBillImport INT NOT NULL,
	IDProduct INT NOT NULL,
	Amount INT DEFAULT 1,
)
GO

CREATE TABLE Client
(
	IDClient INT IDENTITY
		CONSTRAINT PK_IDClient PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Address NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50)
)


CREATE TABLE BillExport
(
	IDBillExport INT IDENTITY
		CONSTRAINT PK_IDBillExport PRIMARY KEY,
	IDClient INT NOT NULL DEFAULT 1,
	DateOut DATETIME NOT NULL,
)
GO

CREATE TABLE BillExportInfo
(
	IDBillExport INT NOT NULL,
	IDProduct INT NOT NULL,
	Amount INT DEFAULT 1,
)

CREATE TABLE Size
(
	IDSize INT IDENTITY
		CONSTRAINT PK_IDSize PRIMARY KEY,
	Size NVARCHAR(10) NOT NULL DEFAULT 'Không'
)
GO




CREATE TABLE Color
(
	IDColor INT IDENTITY
		CONSTRAINT PK_IDColor PRIMARY KEY,
	Color NVARCHAR(20) NOT NULL DEFAULT N'Không'
)

CREATE TABLE Product
(
	IDProduct INT IDENTITY
		CONSTRAINT PK_IDProduct PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL DEFAULT N'Chưa đặt tên',
	IDType INT NOT NULL DEFAULT 1,
	IDSupplier INT NOT NULL DEFAULT 1,
	IDSize INT NOT NULL DEFAULT 1,
	IDColor INT NOT NULL DEFAULT 1,
	Amount INT DEFAULT 1,
	Unit NVARCHAR(50) NOT NULL DEFAULT N'Cái',
	PriceOut DECIMAL(19, 4) DEFAULT 1000,
	PriceIn DECIMAL(19, 4) DEFAULT 1000
)
GO

ALTER TABLE Supplier
ADD 
	CONSTRAINT FK_Supplier_IDBranch
	FOREIGN KEY (IDBranch) 
	REFERENCES Branch(IDBranch)
	ON UPDATE CASCADE ON DELETE SET DEFAULT

ALTER TABLE BillImport
ADD CONSTRAINT FK_BillImport_IDSupplier
	FOREIGN KEY (IDSupplier)
	REFERENCES Supplier(IDSupplier)
	ON UPDATE CASCADE

ALTER TABLE BillExport
ADD CONSTRAINT FK_BillExport_IDClient
	FOREIGN KEY (IDClient)
	REFERENCES Client(IDClient)
	ON UPDATE CASCADE


ALTER TABLE BillImportInfo
ADD CONSTRAINT FK_BillImportInfo_IDBillImport
	FOREIGN KEY (IDBillImport)
	REFERENCES BillImport(IDBillImport)
	ON UPDATE CASCADE,

    CONSTRAINT FK_BillImportInfo_IDProduct
	FOREIGN KEY (IDProduct)
	REFERENCES Product(IDProduct)
	ON UPDATE CASCADE

ALTER TABLE BillExportInfo
ADD CONSTRAINT FK_BillExportInfo_IDBillExport
	FOREIGN KEY (IDBillExport)
	REFERENCES BillExport(IDBillExport)
	ON UPDATE CASCADE,

    CONSTRAINT FK_BillExportInfo_IDProduct
	FOREIGN KEY (IDProduct)
	REFERENCES Product(IDProduct)
	ON UPDATE CASCADE


ALTER TABLE Product
ADD CONSTRAINT FK_Product_IDSupplier
	FOREIGN KEY (IDSupplier)
	REFERENCES Supplier(IDSupplier),
	
	CONSTRAINT FK_Product_IDType
	FOREIGN KEY (IDType)
	REFERENCES Type(IDType)
	ON UPDATE CASCADE ON DELETE SET DEFAULT,

	CONSTRAINT FK_Product_IDColor
	FOREIGN KEY (IDColor)
	REFERENCES Color(IDColor)
	ON UPDATE CASCADE ON DELETE SET DEFAULT,

	CONSTRAINT FK_Product_IDSize
	FOREIGN KEY (IDSize)
	REFERENCES Size(IDSize)
	ON UPDATE CASCADE ON DELETE SET DEFAULT


